select cron.schedule_in_database('GINESYS_AUTO_SETTLEMENT_JOB_QQQQ','*/15 * * * *','call main.db_pro_auto_settle_unpost()','Q');
select cron.schedule_in_database('GINESYS_DATA_SERVICE_2_QQQQ','*/1 * * * *','call main.db_pro_gds2_event_enqueue()','Q');
select cron.schedule_in_database('GINESYS_INVSTOCK_INTRA_LOG_AGG_QQQQ','30 seconds','call main.invstock_intra_log_refresh()','Q');
select cron.schedule_in_database('GINESYS_INVSTOCK_LOG_AGG_QQQQ','30 seconds','call main.invstock_log_refresh()','Q');
select cron.schedule_in_database('GINESYS_PERIOD_CLOSURE_JOB_QQQQ','*/2 * * * *','call main.db_pro_period_closure_dequeue()','Q');
select cron.schedule_in_database('GINESYS_POS_STLM_AUDIT_QQQQ','*/5 * * * *','call main.db_pro_pos_stlm_audit()','Q');
select cron.schedule_in_database('GINESYS_RECALCULATE_TAX_JOB_QQQQ','*/30 * * * *','call main.db_pro_recalculategst()','Q');
select cron.schedule_in_database('GINESYS_STOCK_BOOK_PIPELINE_DELTA_AGG_QQQQ','*/5 * * * *','call db_pro_delta_agg_pipeline_stock()','Q');
select cron.schedule_in_database('GINESYS_STOCK_BOOK_SUMMARY_DELTA_AGG_QQQQ','*/5 * * * *','call db_pro_delta_agg_stock_book_summary()','Q');
select cron.schedule_in_database('GINESYS_STOCK_AGEING_DELTA_AGG_QQQQ','*/5 * * * *','call db_pro_delta_agg_stock_age_analysis()','Q');