select cron.schedule_in_database('GINESYS_AUTO_SETTLEMENT_JOB_OLPL','*/15 * * * *','call main.db_pro_auto_settle_unpost()','pgdev');
select cron.schedule_in_database('GINESYS_DATA_SERVICE_2_OLPL','*/1 * * * *','call main.db_pro_gds2_event_enqueue()','pgdev');
select cron.schedule_in_database('GINESYS_INVSTOCK_INTRA_LOG_AGG_OLPL','30 seconds','call main.invstock_intra_log_refresh()','pgdev');
select cron.schedule_in_database('GINESYS_INVSTOCK_LOG_AGG_OLPL','30 seconds','call main.invstock_log_refresh()','pgdev');
select cron.schedule_in_database('GINESYS_PERIOD_CLOSURE_JOB_OLPL','*/2 * * * *','call main.db_pro_period_closure_dequeue()','pgdev');
select cron.schedule_in_database('GINESYS_POS_STLM_AUDIT_OLPL','*/5 * * * *','call main.db_pro_pos_stlm_audit()','pgdev');
select cron.schedule_in_database('GINESYS_RECALCULATE_TAX_JOB_OLPL','*/30 * * * *','call main.db_pro_recalculategst()','pgdev');
select cron.schedule_in_database('GINESYS_STOCK_BOOK_PIPELINE_DELTA_AGG_OLPL','*/5 * * * *','call db_pro_delta_agg_pipeline_stock()','pgdev');
select cron.schedule_in_database('GINESYS_STOCK_BOOK_SUMMARY_DELTA_AGG_OLPL','*/5 * * * *','call db_pro_delta_agg_stock_book_summary()','pgdev');
select cron.schedule_in_database('GINESYS_STOCK_AGEING_DELTA_AGG_OLPL','*/5 * * * *','call db_pro_delta_agg_stock_age_analysis()','pgdev');